
services:
  - type: web
    name: n8n
    plan: starter                    # web sempre ON; i webhook restano affidabili
    runtime: docker
    dockerfilePath: ./Dockerfile        # percorso del tuo Dockerfile (nella root del repo)
    healthCheckPath: /healthz
    autoDeploy: true                    # facoltativo: true = ogni push fa deploy automatico
    envVars:
      # ---- DB: Supabase Postgres ----
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-eu-central-2.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.bnjwjnhejffssogfmses
      - key: DB_POSTGRESDB_PASSWORD
        value: '%NdkrU$c+bk8VpP'

      # (Opzionale) se vuoi tenere i dati di n8n in uno schema dedicato:
      - key: DB_POSTGRESDB_SCHEMA
        value: n8n

      - key: N8N_RUNNERS_ENABLED
        value: "true"
			- key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # ---- Sicurezza & URL ----
      - key: N8N_ENCRYPTION_KEY
        value: 86145eb6aa37f13e89a89a4fe84404a58fa85258e9773ed77cddbc1eb02f6dcb   # non cambiarla mai
      - key: N8N_PROTOCOL
        value: https
      # Imposta dopo il primo deploy con l'URL reale del servizio:
      - key: WEBHOOK_URL
        value: https://n8n-h3a7.onrender.com

      # (Opzionali utili)
      - key: GENERIC_TIMEZONE
        value: Europe/Rome
      - key: TZ
        value: Europe/Rome
